# Generated by Django 4.2 on 2023-08-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManagedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_tumor', models.CharField(max_length=100)),
                ('num_metastasis', models.PositiveIntegerField()),
                ('ct_images_before', models.ImageField(blank=True, null=True, upload_to='ct_images/')),
                ('ct_images_after', models.ImageField(blank=True, null=True, upload_to='ct_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_info', models.TextField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='details.patient')),
            ],
        ),
    ]
