# Generated by Django 4.2 on 2023-08-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ct_images_after',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ct_images_before',
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='ct_images/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='ct_images_after',
            field=models.ManyToManyField(blank=True, related_name='after_images', to='details.patientimage'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ct_images_before',
            field=models.ManyToManyField(blank=True, related_name='before_images', to='details.patientimage'),
        ),
    ]
