# Generated by Django 4.2 on 2023-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_remove_patient_ct_images_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mark_for_study',
            field=models.BooleanField(default=False),
        ),
    ]
