# Generated by Django 4.2 on 2023-10-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_patient_mark_for_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='control_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.patient')),
                ('photos', models.ManyToManyField(blank=True, related_name='control_photos', to='details.controlphoto')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='patient_controls', to='details.control'),
        ),
    ]
