# Generated by Django 4.2 on 2024-01-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_patient_date_of_birth_patient_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_first_presentation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Control_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='control/')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_images_set', to='details.control')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='control_images',
            field=models.ManyToManyField(blank=True, related_name='control_images', to='details.control_images'),
        ),
    ]
