# Generated by Django 4.2 on 2024-01-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_patient_date_of_first_presentation_control_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='control_images',
        ),
    ]
