# Generated by Django 4.2 on 2024-01-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_remove_control_control_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='num_metastasis',
        ),
        migrations.AddField(
            model_name='patient',
            name='lung_option',
            field=models.CharField(blank=True, choices=[('L', 'Left Lung'), ('R', 'Right Lung'), ('B', 'Both Lungs')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='num_metastasis_left',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='num_metastasis_right',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
